console.log(document.body.firstElementChild)
console.log(document.body.firstChild)
console.log(document.body.lastChild)
console.log(document.body.childNodes)
l=document.getElementsByClassName("js"[0])
console.log(l)