let first=document.getElementById("first")
console.log(first)
let second=document.getElementById("second")
console.log(second)
console.log(first.getAttribute("class"))
console.log(second.getAttribute("class"))
console.log(first.hasAttribute("class"))
console.log(first.hasAttribute("style"))
first.setAttribute("hidden","true")
